- name: Create a Linux VM on OpenShift Virtualization
  hosts: localhost
  gather_facts: false
  collections:
    - kubevirt.core

  tasks:
    - name: Create a VirtualMachine
      kubevirt.core.kubevirt_vm:
        state: present
        name: test-vm
        namespace: linux-vm
        running: true
        spec:
          domain:
            devices:
              disks:
                - name: containerdisk
                  disk:
                    bus: virtio
                - name: cloudinitdisk
                  disk:
                    bus: virtio
            resources:
              requests:
                memory: 1Gi
          volumes:
            - name: containerdisk
              containerDisk:
                image: kubevirt/fedora-cloud-container-disk-demo:latest
            - name: cloudinitdisk
              cloudInitNoCloud:
                userData: |
                  #cloud-config
                  password: fedora
                  chpasswd: { expire: False }
