---
- name: Update RAM of a VM on OpenShift Virtualization with retry on conflict
  hosts: localhost
  gather_facts: no
  collections:
    - kubernetes.core

  vars:
    namespace: linux-vm
    vm_name: fedora-vm
    new_memory: "4Gi"
    max_retries: 5
    retry_delay: 3

  tasks:
    - name: Stop the VM before editing
      k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ namespace }}"
        definition:
          spec:
            running: false

    - name: Initialize retry counter
      set_fact:
        retry_count: 0

    - name: Update VM memory with retry loop
      block:
        - name: Fetch VM info
          k8s_info:
            api_version: kubevirt.io/v1
            kind: VirtualMachine
            namespace: "{{ namespace }}"
            name: "{{ vm_name }}"
          register: vm_info

        - name: Prepare updated VM definition
          set_fact:
            domain_spec: "{{ vm_info.resources[0].spec.template.spec.domain }}"
            updated_domain_spec: "{{ domain_spec | combine({'resources': {'requests': {'memory': new_memory}}}, recursive=True) }}"
            updated_spec_template_spec: "{{ vm_info.resources[0].spec.template.spec | combine({'domain': updated_domain_spec}, recursive=True) }}"
            updated_spec_template: "{{ vm_info.resources[0].spec.template | combine({'spec': updated_spec_template_spec}, recursive=True) }}"
            updated_spec: "{{ vm_info.resources[0].spec | combine({'template': updated_spec_template}, recursive=True) }}"
            updated_vm: >-
              {{
                vm_info.resources[0] | combine(
                  {
                    'spec': updated_spec,
                    'metadata': {
                      'resourceVersion': vm_info.resources[0].metadata.resourceVersion
                    }
                  }, recursive=True
                )
              }}

        - name: Try to apply updated VM definition
          k8s:
            state: present
            definition: "{{ updated_vm }}"
          register: apply_result
          failed_when: "'Conflict' in apply_result.msg"

      rescue:
        - name: Increment retry counter
          set_fact:
            retry_count: "{{ retry_count + 1 }}"

        - name: Fail if max retries reached
          fail:
            msg: "Failed to update VM memory after {{ max_retries }} retries due to conflict."
          when: retry_count >= max_retries

        - name: Pause before retry
          pause:
            seconds: "{{ retry_delay }}"

        - name: Retry the block (meta)
          meta: clear_host_errors

      until: apply_result is succeeded
      retries: "{{ max_retries }}"
      delay: "{{ retry_delay }}"

    - name: Start the VM again
      k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ namespace }}"
        definition:
          spec:
            running: true
